application: taconight
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: jinja2
  version: latest


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images/
  static_dir: images/

# you missed this section. It allows all .css files inside stylesheets
- url: /stylesheets/(.*\.(css)) 
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(css))

- url: /stylesheets/(.*\.(js))
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(js))


- url: /auth/.*
  script: main.application
  login: required

- url: /_admin/.*
  script: main.application
  login: admin      

- url: /.*
  script: main.application

